version: "3"
services:
  api:
    build: .

    # DEV
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

    # PROD
    # command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

    ports: 
      - 8000:8000
    depends_on:
      - postgres
    # env_file: 
    #   - ./.env
    volumes:
      - ./:/usr/src/app:ro
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_PWD=password123
      - DB_NAME=fastapi
      - SECRET_KEY=abc
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MIN=30

    
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=fastapi
      - POSTGRES_PASSWORD=password123
    
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: 