"""''

Revision ID: af17d79e56dc
Revises: d619dcb733c6
Create Date: 2021-12-11 11:06:43.124230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af17d79e56dc'
down_revision = 'd619dcb733c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String))
    # ### end Alembic commands ###
